// A compact hand-picked set of unicode emoji for the composer picker and the
// `:name:` autocomplete. Not the full Unicode set — the ones that actually turn
// up in chat, with search keywords.

export interface EmojiEntry {
  e: string
  /** canonical shortcode (what `:name:` autocomplete matches and inserts) */
  n: string
  /** extra search terms */
  k: string
}

export const EMOJI: EmojiEntry[] = [
  { e: '😀', n: 'grinning', k: 'smile happy' },
  { e: '😃', n: 'smiley', k: 'happy joy' },
  { e: '😄', n: 'smile', k: 'happy laugh' },
  { e: '😁', n: 'grin', k: 'happy' },
  { e: '😆', n: 'laughing', k: 'lol satisfied' },
  { e: '😅', n: 'sweat_smile', k: 'hot relief' },
  { e: '🤣', n: 'rofl', k: 'rolling floor laughing lol' },
  { e: '😂', n: 'joy', k: 'tears laughing lol cry' },
  { e: '🙂', n: 'slight_smile', k: 'smile' },
  { e: '🙃', n: 'upside_down', k: 'silly sarcasm' },
  { e: '😉', n: 'wink', k: 'flirt' },
  { e: '😊', n: 'blush', k: 'smile happy shy' },
  { e: '😇', n: 'innocent', k: 'angel halo' },
  { e: '🥰', n: 'smiling_face_with_three_hearts', k: 'love adore' },
  { e: '😍', n: 'heart_eyes', k: 'love crush' },
  { e: '🤩', n: 'star_struck', k: 'excited eyes stars' },
  { e: '😘', n: 'kissing_heart', k: 'kiss love' },
  { e: '😗', n: 'kissing', k: 'kiss' },
  { e: '😚', n: 'kissing_closed_eyes', k: 'kiss' },
  { e: '😋', n: 'yum', k: 'tongue tasty delicious' },
  { e: '😛', n: 'stuck_out_tongue', k: 'tongue' },
  { e: '😜', n: 'stuck_out_tongue_winking_eye', k: 'tongue wink silly' },
  { e: '🤪', n: 'zany', k: 'goofy crazy silly' },
  { e: '🤨', n: 'raised_eyebrow', k: 'skeptic suspicious' },
  { e: '🧐', n: 'monocle', k: 'inspect think' },
  { e: '🤓', n: 'nerd', k: 'geek glasses' },
  { e: '😎', n: 'sunglasses', k: 'cool' },
  { e: '🥸', n: 'disguise', k: 'incognito glasses' },
  { e: '🤗', n: 'hugging', k: 'hug' },
  { e: '🤔', n: 'thinking', k: 'hmm consider' },
  { e: '🤭', n: 'hand_over_mouth', k: 'oops giggle' },
  { e: '🤫', n: 'shushing', k: 'quiet silence' },
  { e: '🤥', n: 'lying', k: 'pinocchio liar' },
  { e: '😐', n: 'neutral', k: 'meh' },
  { e: '😑', n: 'expressionless', k: 'blank meh' },
  { e: '😶', n: 'no_mouth', k: 'silent speechless' },
  { e: '😏', n: 'smirk', k: 'smug' },
  { e: '😒', n: 'unamused', k: 'meh annoyed' },
  { e: '🙄', n: 'roll_eyes', k: 'annoyed whatever' },
  { e: '😬', n: 'grimacing', k: 'awkward yikes' },
  { e: '😮‍💨', n: 'exhale', k: 'sigh relief' },
  { e: '😌', n: 'relieved', k: 'calm content' },
  { e: '😔', n: 'pensive', k: 'sad down' },
  { e: '😪', n: 'sleepy', k: 'tired' },
  { e: '😴', n: 'sleeping', k: 'zzz tired' },
  { e: '😷', n: 'mask', k: 'sick ill' },
  { e: '🤒', n: 'thermometer_face', k: 'sick fever' },
  { e: '🤕', n: 'head_bandage', k: 'hurt injured' },
  { e: '🤢', n: 'nauseated', k: 'sick gross' },
  { e: '🤮', n: 'vomiting', k: 'sick puke gross' },
  { e: '🤧', n: 'sneezing', k: 'sick tissue' },
  { e: '🥵', n: 'hot_face', k: 'heat sweating' },
  { e: '🥶', n: 'cold_face', k: 'freezing frozen' },
  { e: '😵', n: 'dizzy_face', k: 'confused knocked out' },
  { e: '😵‍💫', n: 'spiral_eyes', k: 'dizzy confused' },
  { e: '🤯', n: 'exploding_head', k: 'mind blown shock' },
  { e: '🤠', n: 'cowboy', k: 'yeehaw hat' },
  { e: '🥳', n: 'partying_face', k: 'celebrate party horn' },
  { e: '😞', n: 'disappointed', k: 'sad' },
  { e: '😟', n: 'worried', k: 'concern' },
  { e: '😤', n: 'triumph', k: 'frustrated steam' },
  { e: '😠', n: 'angry', k: 'mad' },
  { e: '😡', n: 'rage', k: 'mad furious' },
  { e: '🤬', n: 'cursing', k: 'swearing angry' },
  { e: '😳', n: 'flushed', k: 'embarrassed surprised' },
  { e: '🥺', n: 'pleading', k: 'puppy eyes beg' },
  { e: '😢', n: 'cry', k: 'sad tear' },
  { e: '😭', n: 'sob', k: 'cry bawl sad' },
  { e: '😨', n: 'fearful', k: 'scared' },
  { e: '😰', n: 'cold_sweat', k: 'anxious nervous' },
  { e: '😱', n: 'scream', k: 'shock fear' },
  { e: '😖', n: 'confounded', k: 'frustrated' },
  { e: '😣', n: 'persevere', k: 'struggle' },
  { e: '😩', n: 'weary', k: 'tired ugh' },
  { e: '😫', n: 'tired_face', k: 'exhausted ugh' },
  { e: '🥱', n: 'yawning', k: 'bored tired' },
  { e: '😤', n: 'huff', k: 'annoyed' },
  { e: '🤐', n: 'zipper_mouth', k: 'secret quiet' },
  { e: '🫡', n: 'saluting', k: 'salute yes sir respect' },
  { e: '🫠', n: 'melting', k: 'hot embarrassed' },
  { e: '🫥', n: 'dotted_line_face', k: 'invisible' },
  { e: '😈', n: 'smiling_imp', k: 'devil evil' },
  { e: '👿', n: 'imp', k: 'devil angry' },
  { e: '💀', n: 'skull', k: 'dead dying lol' },
  { e: '💩', n: 'poop', k: 'crap' },
  { e: '🤡', n: 'clown', k: 'joker' },
  { e: '👻', n: 'ghost', k: 'boo spooky' },
  { e: '👽', n: 'alien', k: 'ufo' },
  { e: '🤖', n: 'robot', k: 'bot' },
  { e: '🎃', n: 'jack_o_lantern', k: 'halloween pumpkin' },
  { e: '😺', n: 'smiley_cat', k: 'cat happy' },
  { e: '👋', n: 'wave', k: 'hi hello bye' },
  { e: '🤚', n: 'raised_back_of_hand', k: 'stop' },
  { e: '✋', n: 'raised_hand', k: 'stop high five' },
  { e: '🖐️', n: 'hand_splayed', k: 'five stop' },
  { e: '👌', n: 'ok_hand', k: 'okay perfect' },
  { e: '🤌', n: 'pinched_fingers', k: 'italian chef kiss' },
  { e: '🤏', n: 'pinching_hand', k: 'small tiny bit' },
  { e: '✌️', n: 'v', k: 'peace victory' },
  { e: '🤞', n: 'crossed_fingers', k: 'luck hope' },
  { e: '🫰', n: 'hand_with_index_finger_and_thumb_crossed', k: 'money love' },
  { e: '🤟', n: 'love_you_gesture', k: 'ily rock' },
  { e: '🤘', n: 'metal', k: 'rock horns' },
  { e: '🤙', n: 'call_me_hand', k: 'shaka hang loose' },
  { e: '👈', n: 'point_left', k: 'this' },
  { e: '👉', n: 'point_right', k: 'this' },
  { e: '👆', n: 'point_up_2', k: 'this above' },
  { e: '👇', n: 'point_down', k: 'this below' },
  { e: '☝️', n: 'point_up', k: 'one this' },
  { e: '👍', n: 'thumbsup', k: '+1 yes agree like approve' },
  { e: '👎', n: 'thumbsdown', k: '-1 no disagree dislike' },
  { e: '✊', n: 'fist', k: 'power solidarity' },
  { e: '👊', n: 'punch', k: 'fist bump bro' },
  { e: '🤛', n: 'left_facing_fist', k: 'bump' },
  { e: '🤜', n: 'right_facing_fist', k: 'bump' },
  { e: '👏', n: 'clap', k: 'applause praise' },
  { e: '🙌', n: 'raised_hands', k: 'praise celebrate hooray' },
  { e: '🫶', n: 'heart_hands', k: 'love' },
  { e: '👐', n: 'open_hands', k: 'hug' },
  { e: '🤲', n: 'palms_up', k: 'pray beg' },
  { e: '🙏', n: 'pray', k: 'please thanks thank you hope namaste' },
  { e: '🤝', n: 'handshake', k: 'deal agree' },
  { e: '💪', n: 'muscle', k: 'strong flex gym' },
  { e: '🫵', n: 'index_pointing_at_the_viewer', k: 'you' },
  { e: '👀', n: 'eyes', k: 'look watch shifty' },
  { e: '🧠', n: 'brain', k: 'smart big brain' },
  { e: '❤️', n: 'heart', k: 'love red' },
  { e: '🧡', n: 'orange_heart', k: 'love' },
  { e: '💛', n: 'yellow_heart', k: 'love' },
  { e: '💚', n: 'green_heart', k: 'love' },
  { e: '💙', n: 'blue_heart', k: 'love' },
  { e: '💜', n: 'purple_heart', k: 'love' },
  { e: '🖤', n: 'black_heart', k: 'love dark' },
  { e: '🤍', n: 'white_heart', k: 'love' },
  { e: '🤎', n: 'brown_heart', k: 'love' },
  { e: '💔', n: 'broken_heart', k: 'sad heartbreak' },
  { e: '❤️‍🔥', n: 'heart_on_fire', k: 'love passion' },
  { e: '💕', n: 'two_hearts', k: 'love' },
  { e: '💯', n: '100', k: 'hundred perfect score keep it' },
  { e: '💢', n: 'anger', k: 'mad symbol' },
  { e: '💥', n: 'boom', k: 'explosion collision' },
  { e: '💫', n: 'dizzy', k: 'stars' },
  { e: '💦', n: 'sweat_drops', k: 'water splash' },
  { e: '💨', n: 'dash', k: 'wind fast run' },
  { e: '🕳️', n: 'hole', k: 'pit' },
  { e: '💬', n: 'speech_balloon', k: 'comment chat' },
  { e: '💭', n: 'thought_balloon', k: 'think' },
  { e: '🔥', n: 'fire', k: 'lit hot burn flame' },
  { e: '⭐', n: 'star', k: 'favorite' },
  { e: '🌟', n: 'star2', k: 'glow sparkle' },
  { e: '✨', n: 'sparkles', k: 'shiny magic clean new' },
  { e: '⚡', n: 'zap', k: 'lightning fast electric' },
  { e: '☀️', n: 'sunny', k: 'sun weather' },
  { e: '🌈', n: 'rainbow', k: 'pride colors' },
  { e: '☁️', n: 'cloud', k: 'weather' },
  { e: '❄️', n: 'snowflake', k: 'cold winter' },
  { e: '⛄', n: 'snowman', k: 'winter' },
  { e: '🌊', n: 'ocean', k: 'wave water sea' },
  { e: '🎉', n: 'tada', k: 'party celebrate congrats yay' },
  { e: '🎊', n: 'confetti_ball', k: 'party celebrate' },
  { e: '🎈', n: 'balloon', k: 'party birthday' },
  { e: '🎁', n: 'gift', k: 'present birthday' },
  { e: '🏆', n: 'trophy', k: 'win award champion' },
  { e: '🥇', n: 'first_place', k: 'gold medal win' },
  { e: '🎯', n: 'dart', k: 'target bullseye goal' },
  { e: '🚀', n: 'rocket', k: 'launch ship fast space' },
  { e: '🛠️', n: 'tools', k: 'fix build wip' },
  { e: '🔧', n: 'wrench', k: 'fix tool config' },
  { e: '🔨', n: 'hammer', k: 'build fix' },
  { e: '🐛', n: 'bug', k: 'insect defect issue' },
  { e: '💻', n: 'computer', k: 'laptop code' },
  { e: '🖥️', n: 'desktop', k: 'computer monitor' },
  { e: '⌨️', n: 'keyboard', k: 'type' },
  { e: '📱', n: 'iphone', k: 'phone mobile' },
  { e: '💾', n: 'floppy_disk', k: 'save disk' },
  { e: '📦', n: 'package', k: 'box ship release' },
  { e: '📈', n: 'chart_increasing', k: 'graph up growth' },
  { e: '📉', n: 'chart_decreasing', k: 'graph down loss' },
  { e: '📝', n: 'memo', k: 'note write edit pencil' },
  { e: '📌', n: 'pushpin', k: 'pin' },
  { e: '📍', n: 'round_pushpin', k: 'location pin here' },
  { e: '🔗', n: 'link', k: 'url chain' },
  { e: '🔒', n: 'lock', k: 'secure private' },
  { e: '🔑', n: 'key', k: 'password access' },
  { e: '🔔', n: 'bell', k: 'notification alert' },
  { e: '🔕', n: 'no_bell', k: 'mute silent' },
  { e: '⏰', n: 'alarm_clock', k: 'time wake' },
  { e: '⌛', n: 'hourglass', k: 'time wait' },
  { e: '✅', n: 'white_check_mark', k: 'done yes check ok complete' },
  { e: '☑️', n: 'ballot_box_with_check', k: 'checkbox done' },
  { e: '✔️', n: 'heavy_check_mark', k: 'done yes' },
  { e: '❌', n: 'x', k: 'no cross wrong fail' },
  { e: '❎', n: 'negative_squared_cross_mark', k: 'no' },
  { e: '➕', n: 'heavy_plus_sign', k: 'add plus' },
  { e: '➖', n: 'heavy_minus_sign', k: 'minus remove' },
  { e: '❓', n: 'question', k: 'help ask' },
  { e: '❗', n: 'exclamation', k: 'warning important' },
  { e: '⚠️', n: 'warning', k: 'caution alert' },
  { e: '🚫', n: 'no_entry_sign', k: 'ban forbidden stop' },
  { e: '💡', n: 'bulb', k: 'idea light' },
  { e: '🔍', n: 'mag', k: 'search find zoom' },
  { e: '👁️', n: 'eye', k: 'look see' },
  { e: '🎵', n: 'musical_note', k: 'music song' },
  { e: '🎶', n: 'notes', k: 'music song' },
  { e: '☕', n: 'coffee', k: 'cafe morning' },
  { e: '🍺', n: 'beer', k: 'drink pub' },
  { e: '🍕', n: 'pizza', k: 'food' },
  { e: '🍔', n: 'hamburger', k: 'food burger' },
  { e: '🎂', n: 'birthday', k: 'cake party' },
  { e: '🍰', n: 'cake', k: 'dessert' },
  { e: '🐶', n: 'dog', k: 'puppy pet' },
  { e: '🐱', n: 'cat', k: 'kitten pet' },
  { e: '🦄', n: 'unicorn', k: 'magic' },
  { e: '🐢', n: 'turtle', k: 'slow' },
  { e: '🐇', n: 'rabbit2', k: 'bunny fast' },
  { e: '🦅', n: 'eagle', k: 'bird' },
  { e: '🌵', n: 'cactus', k: 'plant desert' },
  { e: '🌹', n: 'rose', k: 'flower love' },
  { e: '🌻', n: 'sunflower', k: 'flower' },
  { e: '🍀', n: 'four_leaf_clover', k: 'luck' },
  { e: '🎮', n: 'video_game', k: 'gaming controller play' },
  { e: '🕹️', n: 'joystick', k: 'game arcade' },
  { e: '🎲', n: 'game_die', k: 'dice random' },
  { e: '📢', n: 'loudspeaker', k: 'announce shout' },
  { e: '📣', n: 'mega', k: 'announce cheer' },
  { e: '🙈', n: 'see_no_evil', k: 'monkey hide oops' },
  { e: '🙉', n: 'hear_no_evil', k: 'monkey' },
  { e: '🙊', n: 'speak_no_evil', k: 'monkey oops' },
  { e: '💤', n: 'zzz', k: 'sleep tired bored' },
  { e: '🧵', n: 'thread', k: 'sewing' },
  { e: '♻️', n: 'recycle', k: 'reuse green' },
  { e: '🆕', n: 'new', k: 'fresh' },
  { e: '🆗', n: 'ok', k: 'okay' },
  { e: '🔴', n: 'red_circle', k: 'record live' },
  { e: '🟢', n: 'green_circle', k: 'online go' },
  { e: '🟡', n: 'yellow_circle', k: 'idle' },
  { e: '🔵', n: 'blue_circle', k: 'dot' }
]

/** Filter the set by a fuzzy term against name + keywords. Empty → the lot. */
export function searchEmoji(term: string, limit = 60): EmojiEntry[] {
  const t = term.trim().toLowerCase().replace(/:/g, '')
  if (!t) return EMOJI.slice(0, limit)
  const starts: EmojiEntry[] = []
  const contains: EmojiEntry[] = []
  for (const it of EMOJI) {
    if (it.n === t || it.e === term) return [it]
    if (it.n.startsWith(t)) starts.push(it)
    else if (it.n.includes(t) || it.k.includes(t)) contains.push(it)
  }
  return [...starts, ...contains].slice(0, limit)
}
